### ISSUE TITLE
Spatialization doesn't work in Safari

### ISSUE THREAD

**Issue by PyrApple** [polarch/JSAmbisonics#5]
Something appends when you move the source in e.g. `examples/hoa-panner.hmtl`, yet it rather feels like random frequency filtering than binaural spatialization.

**Comment by polarch** [comment]
Yeah,
It never worked in Safari, and I couldn't care less to be honest, FF and Chrome support (OS independent) is more important. They seem to have some broken WebAudio implementation, my guess is something in channel splitter/merger probably. In any case , it may be an easy fix, but we shouldn't adapt the code for inconsistencies, they should fix their implementation..

Archontis

On 11 Jul 2016 4:39 p.m., David Poirier-Quinot notifications@github.com wrote:

Something appends when you move the source in e.g. examples/hoa-panner.hmtl, yet it rather feels like random frequency filtering than binaural spatialization.

**Comment by PyrApple** [comment]
agreed

**Comment by PyrApple** [comment]
fixed in [latest commit](https://github.com/polarch/JSAmbisonics/pull/6)
